server:
  port: 8021
spring:
  application:
    name: User-Service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.7:8848
        username: nacos
        password: fangxin12300.
        cluster-name: HUABEI
        weight: 0.5
      config:
        file-extension: yml
        server-addr: 192.168.31.7:8848
    loadbalancer:
      nacos:
        enabled: true