server:
  port: 8082
spring:
  application:
    name: Borrow-Service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.7:8848
        username: nacos
        password: fangxin12300.
        cluster-name: ZhengZhou
    openfeign:
      compression:
        request:
          enabled: true
        response:
          enabled: true
    loadbalancer:
      nacos:
        enabled: true